apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: petclinic
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: quay.io/camillegr/petclinic:latest
        ports:
        - name: http-port
          containerPort: 8080
        env:
        - name: MYSQL_URL
          value: jdbc:mysql://mariadb-service.petclinic.svc/petclinic
        readinessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 60
          periodSeconds: 30
